services:
  - type: web
    name: sura-scraper-api
    env: docker
    buildCommand: docker build -t sura-scraper .
    startCommand: docker run -p 8080:8080 sura-scraper
    healthCheckPath: /health
    envVars:
      - key: API_SECRET_KEY
        generateValue: true
      - key: API_USERNAME
        value: admin
      - key: API_PASSWORD
        generateValue: true  # Cambiar para mayor seguridad
      - key: HEADLESS
        value: "true"
      - key: TIMEOUT
        value: "30"
      - key: MAX_RESULTS
        value: "10"
      - key: LOG_LEVEL
        value: INFO
      - key: DEBUG
        value: "false"